### ISSUE TITLE
Missing organiser image on About page

### ISSUE THREAD

**Issue by loicplaire** [react-rally/www#15]
I am guessing this is the best way to report this... ❓

"Sunny Legget" profile image returns a `403 Forbidden` status code and is not displayed on the page as per the screenshot below. 

![image](https://user-images.githubusercontent.com/1925075/38713999-6d7347c4-3f17-11e8-8961-7a20825c8609.png)

![image](https://user-images.githubusercontent.com/1925075/38713912-191a079e-3f17-11e8-96d0-e8a0c54a1443.png)

**Comment by mzabriskie** [comment]
Fixed. Thanks!
